/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyButton {
        "appearance": string;
        "disabled": boolean;
        "text": string;
    }
    interface MyButtonShadow {
        "appearance": string;
        "disabled": boolean;
        "text": string;
    }
}
declare global {
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLMyButtonShadowElement extends Components.MyButtonShadow, HTMLStencilElement {
    }
    var HTMLMyButtonShadowElement: {
        prototype: HTMLMyButtonShadowElement;
        new (): HTMLMyButtonShadowElement;
    };
    interface HTMLElementTagNameMap {
        "my-button": HTMLMyButtonElement;
        "my-button-shadow": HTMLMyButtonShadowElement;
    }
}
declare namespace LocalJSX {
    interface MyButton {
        "appearance"?: string;
        "disabled"?: boolean;
        "onOn-click"?: (event: CustomEvent<any>) => void;
        "text"?: string;
    }
    interface MyButtonShadow {
        "appearance"?: string;
        "disabled"?: boolean;
        "onOn-click"?: (event: CustomEvent<any>) => void;
        "text"?: string;
    }
    interface IntrinsicElements {
        "my-button": MyButton;
        "my-button-shadow": MyButtonShadow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-button": LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
            "my-button-shadow": LocalJSX.MyButtonShadow & JSXBase.HTMLAttributes<HTMLMyButtonShadowElement>;
        }
    }
}
